import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "react-datepicker/dist/react-datepicker-cssmodules.css";
import "react-datepicker/dist/react-datepicker.css";

import { Toast } from "@/components";
import CustomSWRConfig from "@/plugins/swr";
import "@/styles/globals.css";
const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Bandung Coders - By @bacodteam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="/icons/icon-192x192.png"
          type="image/png"
          sizes="192x192"
          rel="icon"
        />
        <link
          href="/icons/icon-192x192.png"
          type="image/png"
          sizes="256x256"
          rel="icon"
        />
        <link
          href="/icons/icon-192x192.png"
          type="image/png"
          sizes="384x384"
          rel="icon"
        />
        <link
          href="/icons/icon-192x192.png"
          type="image/png"
          sizes="512x512"
          rel="icon"
        />
        <link href="/manifest.json" rel="manifest" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={inter.className}>
        <CustomSWRConfig>{children}</CustomSWRConfig>
        <Toast />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator) {
                window.addEventListener('load', function() {
                  navigator.serviceWorker.register('/service-worker.js').then(function(registration) {
                    console.log('ServiceWorker registration successful with scope: ', registration.scope);
                  }, function(err) {
                    console.log('ServiceWorker registration failed: ', err);
                  });
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
